### ISSUE TITLE
Square blocks instead of some icons

### ISSUE THREAD

**Issue by kilometrix** [vejnoe/weather-in-your-calendar#2]
Browser: Google Chrome 74.0.3729.131
OS: Windows 7
Site: calendar.google.com

A calendar for Minsk was added. As you can see, some icons for weather states are not recognized and replaced by square blocks:

![Безымянный](https://user-images.githubusercontent.com/18598133/57773157-a48a7000-7717-11e9-83cc-203d28dc7bf7.png)

I tried some Chrome extentions that parse current webpage and replace special symbols by emojies, but it did not help.

**Comment by vejnoe** [comment]
Hi @kilometrix, thanks for your feedback! It looks like Windows 7 do not support all emojis, maybe this link will help? https://blog.getemoji.com/post/82224498347/how-to-use-emoji-in-windows-7
