### ISSUE TITLE
Not working with updated OpenWeather API - Free plan

### ISSUE THREAD

**Issue by patrickrushton** [vejnoe/weather-in-your-calendar#3]
OpenWeather have migrated free accounts to their One Call API. It would be great to have a version that works with that (I wanted to create a version that does not include "Location" in the calendar event to have a cleaner view in macOS Calendar)

[https://openweathermap.org/api/one-call-api](https://openweathermap.org/api/one-call-api )

**Comment by patrickrushton** [comment]
I was able to get it working with the One Call API by using longitude and latitude in the request and swapping out "list" for "daily" in the foreach loop.

**Comment by vejnoe** [comment]
Hi @patrickrushton sorry for a late late reply, I'm using this script for my [Weather in your Calendar](https://weather.vejnoe.dk/) so would like to keep it on the 16 days API. But glad you got it to work!
But I just updated the script with your idea about an option to hide the calendar. If you add `&location=hide` to the URL it should work.

**Comment by vejnoe** [comment]
But it would be nice with this being an option in the script where your could choose 7 or 16 days API maybe? Or should it be in a seperat version?

**Comment by patrickrushton** [comment]
For my needs the 16 day version is fine!
